- id: morning_mode
  alias: "Morning Mode"
  trigger:
    - platform: state
      entity_id: input_boolean.sleep_mode
      to: 'off'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.chambre
        temperature: 8
        operation_mode: Heat
    - service: climate.set_temperature
      data:
        entity_id: climate.salon
        temperature: 8
        operation_mode: Heat
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.at_home
    - delay: 00:30:00
    - service: light.turn_on
      data:
        entity_id: light.salon
        flash: short
    - service: climate.set_temperature
      data:
        entity_id: climate.chambre
        temperature: 18
        operation_mode: Heat
    - service: climate.set_temperature
      data:
        entity_id: climate.salon
        temperature: 20.5
        operation_mode: Heat

- id: kodi_paused
  alias: Media player paused/stopped
  trigger:
  - entity_id: media_player.kodi
    from: playing
    platform: state
  condition:
    - condition: time
      after: '20:00:00'
      before: '08:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.living_room_at_night

- id: kodi_playing
  alias: Media player starts at night
  trigger:
  - platform: state
    entity_id: media_player.kodi
    to: playing
  - platform: state
    entity_id: device_tracker.ps4
    to: 'home'
  condition:
    - condition: time
      after: '20:00:00'
      before: '08:00:00'
  action:
  - service: light.turn_off 
    entity_id: light.plafonnier
  - service: scene.turn_on
    entity_id: scene.living_room_cinema

- id: kodi_playing_day
  alias: Media player playing during day
  trigger:
  - platform: state
    entity_id: media_player.kodi
    to: playing
  - platform: state
    entity_id: device_tracker.ps4
    to: 'home'
  action:
  - service: light.turn_off 
    entity_id: light.plafonnier

- id: mild_lights_after_dark
  alias: Mild lights in the evening
  trigger:
    platform: time
    at: '18:00:00'
  condition:
    - condition: state
      entity_id: light.commode
      state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.living_room_at_night

- id: lights_on_when_home_day
  alias: Turn on lights when anyone gets home (day)
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion
      to: 'on'
      from: 'off'
  condition:
    - condition: time
      after: '08:00:00'
      before: '19:00:00'
    - condition: state
      entity_id: light.commode
      state: 'off'
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_normal_fast
    - service: notify.pushbullet
      data_template:
        title: "Someone home"
        message: "Sensor triggered at {{ states.sensor.date__time.state }}"

- id: lights_on_when_home_night
  alias: Turn on lights when anyone gets home (night)
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion
      to: 'on'
      from: 'off'
  condition:
    - condition: time
      after: '19:00:00'
      before: '08:00:00'
    - condition: state
      entity_id: light.commode
      state: 'off'
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_normal
    - service: notify.pushbullet
      data_template:
        title: "Someone home"
        message: "Sensor triggered at {{ states.sensor.date__time.state }}"

- id: red_light_at_night
  alias: "Presence detected during night, light red lights"
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion
      to: 'on'
      from: 'off'
  condition:
    - condition: time
      after: '22:00:00'
      before: '07:00:00'
    - condition: state
      entity_id: light.commode
      state: 'off'
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'on'
  action:
    - service: light.turn_on 
      entity_id: light.commode
      data:
        brightness: 125
        color_name: 'red'
        transition: 5
    - delay: 00:05:00
    - service: light.turn_off 
      entity_id: light.commode
      data:
        transition: 300

- id: turn_off_lights_when_noone_home
  alias: Turn off the lights when no one is home
  trigger:
    platform: state
    entity_id: device_tracker.lucas_oneplus3t
    to: 'not_home'
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition:
    - condition: state
      entity_id: binary_sensor.living_room_motion
      state: 'off'
      for:
        hours: 0
        minutes: 5
        seconds: 0
  action:
    - service: scene.turn_on
      entity_id: scene.lights_off
    - service: notify.pushbullet
      data_template:
        title: "Lights turned off"
        message: "Turned off the lights at {{ states.sensor.date__time.state }}"

- id: begin_sleep_mode
  alias: "Begin sleep mode when turning on bedroom at night"
  trigger:
    platform: state
    entity_id: light.chambre
    to: 'on'
  condition:
    - condition: time
      after: '22:00:00'
      before: '08:00:00'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.salon
        temperature: 19
        operation_mode: Heat
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.sleep_mode
    - service: scene.turn_on
      entity_id: scene.living_room_cinema
    - delay: 00:02:00
    - service: scene.turn_on
      entity_id: scene.living_room_red
    - delay: 00:02:00
    - service: scene.turn_on
      entity_id: scene.living_room_off

- id: begin_morning_mode
  alias: "Begin morning mode when entering living room in the morning"
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion
      to: 'on'
  condition:
    - condition: time
      after: '07:00:00'
      before: '11:00:00'
    - condition: state
      entity_id: light.commode
      state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_cinema
    - delay: 00:00:10
    - service: scene.turn_on
      entity_id: scene.living_room_normal
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.sleep_mode

- id: work_timer
  alias: "Notify user that he started working a while ago"
  trigger:
    platform: state
    entity_id: input_boolean.sleep_mode
    to: 'off'
    for:
      hours: 9
      minutes: 30
      seconds: 0
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: device_tracker.lucas_oneplus3t
      state: 'home'
  action:
    - service: light.turn_on
      data:
        entity_id: light.salon
        flash: short
    - service: light.turn_on
      data:
        entity_id: light.salon
        flash: short

- id: set_at_home_mode
  alias: "Set at_home if I was home during the day"
  trigger:
    platform: time
    minutes: '/30'
    seconds: 00
  condition:
    - condition: state
      entity_id: input_boolean.at_home
      state: 'off'
    - condition: state
      entity_id: device_tracker.lucas_oneplus3t
      state: 'home'
    - condition: time
      after: '09:00:00'
      before: '20:30:00'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.at_home

- id: turn_on_heater
  alias: "Turn on the heater if at_home"
  trigger:
    platform: time
    at: '20:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.at_home
      state: 'on'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.chambre
        temperature: 20.5
        operation_mode: Heat

- id: disable_heaters
  alias: "Disable heaters if no one at home today"
  trigger:
    platform: time
    at: '20:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.at_home
      state: 'off'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.chambre
        temperature: 8
        operation_mode: Heat
    - service: climate.set_temperature
      data:
        entity_id: climate.salon
        temperature: 8
        operation_mode: Heat
    - service: notify.pushbullet
      data_template:
        title: "Disabling heaters"
        message: "Disabled at {{ states.sensor.date__time.state }}"

- id: reduce_heater_at_night
  alias: "Reduce the heater temperature at night once the bedroom lights are off"
  trigger:
    platform: state
    entity_id: light.chambre
    to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'on'
  action:
    - delay: 00:30:00
    - service: climate.set_temperature
      data:
        entity_id: climate.chambre
        temperature: 18.5
        operation_mode: Heat

- id: warn_when_new_device_on_router
  alias: "Warn me when a new device connects on my WiFi"
  trigger:
    platform: event
    event_type: device_tracker_new_device
  action:
    - service: notify.pushbullet
      data_template:
        title: "New WiFi connection"
        message: >
          New device:
            {{trigger.event.data.host_name}}
            {{trigger.event.data.entity_id}}
